FROM mambaorg/micromamba:1.5.8

# $ docker build . -t microbiomedata/meta_t:latest --build-arg http_proxy=http://proxyout.lanl.gov:8080 --build-arg https_proxy=http://proxyout.lanl.gov:8080
# $ docker login
# $ docker push microbiomedata/meta_t:latest

LABEL version="0.0.5"
LABEL software="NMDC_metatranscriptomics workflow"
LABEL tags="bioinformatics"

ENV container docker

# desired conda environment in a yaml file
# Copy the yaml file into your docker image 
COPY --chown=$MAMBA_USER:$MAMBA_USER env.yaml /tmp/env.yaml
# pass the yaml file as a parameter to micromamba via the --file switch
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes


# # add directory relative to working directory
# ADD ../pyp_metat/* /opt/conda/bin/pyp_metat/

# # add to env
# ENV PATH="${PATH}:/opt/conda/bin/pyp_metat"

CMD ["/bin/bash"]
