name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'version.txt'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      
      - name: Create bundle zip
        run: zip -r bundle.zip wdls/* pyp_metat/* scripts/*

      - name: Create Release
        run: gh release create ${{ env.VERSION }} wdls/metaT.wdl bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}